/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import entity.Customer;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import manager.CustomerManager;

/**
 *
 * @author hau
 */
public class Add_Dialog extends javax.swing.JDialog {

    private CustomerManager myManager;

    /**
     * Creates new form Add_Dialog
     */
    public Add_Dialog(CustomerManager myManager, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.myManager = myManager;
        this.addListener();
    }

    private void addListener() {

        this.btnSubmit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (doValidate()) {
                    doAdd();
                    doExit();
                }
            }
        });
        this.btnClear.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClear();
            }
        });

    }

    private void doAdd() {
        int billNumber;//
        String customerName, pet, phoneNum, serviceUsed;//
        float price;//
        int quantity;//
        boolean paymentStatus;

        billNumber = Integer.parseInt(this.txtID.getText());

        customerName = this.txtName.getText();
        pet = this.txtPet.getText();

        phoneNum = this.txtPhone.getText();
        serviceUsed = (String) this.cbxAnimal.getSelectedItem();
        quantity = Integer.parseInt(this.txtQuantity.getText());
        price = Float.parseFloat(this.txtPrice.getText());
        StringBuilder detail = new StringBuilder();
        if (this.btnYes.isSelected()) {
            paymentStatus = true;
        } else {
            paymentStatus = false;
        }
        Customer customer = new Customer(billNumber, customerName, pet, phoneNum, serviceUsed, price, quantity, paymentStatus);
        if (this.myManager.addCustomer(customer)) {
            JOptionPane.showMessageDialog(this, "Successful");
            this.doClear();
            this.refreshParent();
        } else {
            detail.append("Unsuccessful");
            if (myManager.getAdminStatus()) {
                detail.append(", please enter password first ");
            }
           JOptionPane.showMessageDialog(this, detail);
        }
        System.out.println(customer.toString());
    }

    private void doExit() {
        this.dispose();
    }

    private void doClear() {
        this.txtID.setText("");
        this.txtName.setText("");
        this.txtPrice.setText("");
        this.txtPhone.setText("");
        this.btnYes.setSelected(true);
        this.cbxAnimal.setSelectedIndex(0);
        this.lblError.setText("...");

    }

    private boolean doValidate() {
        boolean isValid = true;

        if (this.txtID.getText().length() == 0) {
            isValid = false;
            this.lblError.setText("Bill ID can not be blank");
        }
        if (this.txtName.getText().length() == 0) {
            isValid = false;
            this.lblError.setText("ID can not be blank");
        }
        if (this.txtPhone.getText().length() < 10) {
            isValid = false;
            this.lblError.setText("Phone number not long enough or not filled");
        }

        try {
            Float.parseFloat(this.txtPrice.getText());
        } catch (Exception exx) {
            isValid = false;
            this.lblError.setText("Price not filled");

        }

        return isValid;
    }

    private void refreshParent() {
        MainFrame myBoss = (MainFrame) this.getParent();
        myBoss.doBackup();
        myBoss.refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentStatus = new javax.swing.ButtonGroup();
        lbPaymentStatus = new javax.swing.JLabel();
        lbPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lbPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lbQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        cbxAnimal = new javax.swing.JComboBox<>();
        lbID = new javax.swing.JLabel();
        lbService = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnYes = new javax.swing.JRadioButton();
        lbName = new javax.swing.JLabel();
        btnNo = new javax.swing.JRadioButton();
        txtName = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        lblPet = new javax.swing.JLabel();
        txtPet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbPaymentStatus.setText("Đơn đã được thanh toán");

        lbPhone.setText("Phone");

        txtPhone.setColumns(10);

        lbPrice.setText("Price");
        lbPrice.setToolTipText("");

        txtPrice.setColumns(6);
        txtPrice.setText(" ");

        lbQuantity.setText("Quantity");
        lbQuantity.setToolTipText("");

        txtQuantity.setColumns(3);
        txtQuantity.setText("1");

        cbxAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Medicine", "Pet Keeping" }));
        cbxAnimal.setToolTipText("");
        cbxAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbxAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAnimalActionPerformed(evt);
            }
        });

        lbID.setText("Bill Number");

        lbService.setText("Service");

        txtID.setColumns(10);

        paymentStatus.add(btnYes);
        btnYes.setSelected(true);
        btnYes.setText("Yes");

        lbName.setText("Customer Name");
        lbName.setToolTipText("");

        paymentStatus.add(btnNo);
        btnNo.setText("No");

        txtName.setColumns(10);

        btnSubmit.setBackground(new java.awt.Color(51, 51, 255));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");

        lblError.setText("...");

        btnClear.setBackground(new java.awt.Color(51, 51, 255));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblPet.setText("Customer pet");
        lblPet.setToolTipText("");

        txtPet.setColumns(10);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add customer's information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPaymentStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNo))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbService)
                                        .addComponent(lbPhone)
                                        .addComponent(lbID)
                                        .addComponent(lbName)
                                        .addComponent(lblPet)
                                        .addComponent(lbPrice))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbQuantity)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtID)
                                        .addComponent(txtName)
                                        .addComponent(txtPet)
                                        .addComponent(txtPhone)
                                        .addComponent(cbxAnimal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPet)
                    .addComponent(txtPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbService))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuantity)
                    .addComponent(lbPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPaymentStatus)
                    .addComponent(btnYes)
                    .addComponent(btnNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void cbxAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JRadioButton btnYes;
    private javax.swing.JComboBox<String> cbxAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPaymentStatus;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbQuantity;
    private javax.swing.JLabel lbService;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPet;
    private javax.swing.ButtonGroup paymentStatus;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPet;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
